### ISSUE TITLE
[Help] with Cldr.DateTime.Formatter is not available

### ISSUE THREAD

**Issue by coladarci** [elixir-cldr/cldr_dates_times#14] opened 2020-05-30 16:09 UTC
When doing this locally:
`Cldr.DateTime.to_string(~N[2020-05-28 20:48:08], format: "EE, MMM d, y")`
All works as I'd expect; I get back `{:ok, "Thu, May 28, 2020"}`

But when my app is compiled into our staging environment, the same code results in:

```
function Utils.Cldr.DateTime.Formatter.format/4 is undefined (module Utils.Cldr.DateTime.Formatter is not available)
```

I'm having a hard time understanding what could lead to this working locally and in my tests but not when compiled. 

This is how I am `use`ing Cldr
```
defmodule Utils.Cldr do
  @moduledoc false

  use Cldr,
    default_locale: "en",
    locales: ["en"],
    providers: [Cldr.Calendar, Cldr.DateTime, Cldr.Number],
    generate_docs: false
```

Any theories? Thanks a bunch as always...

**Comment by kipcole9** [comment] 2020-05-30 23:43
I don't think its related to an umbrella app; I created a new umbrella and compiled and the files are there.

And I'm a docker neophyte so it'll take a little while for me to replicate the environment. I'm on it ....

**Comment by kipcole9** [comment] 2020-05-30 23:50
Confirmed that a basic release builds correctly (well at least all the BEAM files are there). On to docker-land.

**Comment by kipcole9** [comment] 2020-05-31 01:43
I am perplexed and not sure how to further diagnose this. 

I created a minimal dockerfile based on your `Dockerfile` except I copied the whole app source tree:
```
####################
# Stage 1: builder #
####################

FROM hexpm/elixir:1.10.2-erlang-22.2.8-alpine-3.11.3 as builder

RUN apk --no-cache --update upgrade && \
  apk --no-cache add openssh alpine-sdk coreutils curl bash

RUN mix local.hex --force && \
  mix local.rebar --force

WORKDIR /app

# Just copy the whole app source tree
COPY . /app/

ENV MIX_ENV prod

RUN mix do deps.get, deps.compile, release

####################
# Stage 2: runtime #
####################

FROM alpine:3.11.6

RUN apk --no-cache --update upgrade && \
  apk --no-cache add openssl ncurses alpine-sdk coreutils curl bash

WORKDIR /app

COPY --from=builder /app/_build/prod/rel/what/ /app/

# CMD ["/bin/bash"]
```

Then run build and run the container interactively and checked the contents and everything is there. Admittedly not an umbrella.
```bash
kip@Kips-iMac-Pro what % docker run --interactive --tty what
/app # ls lib/what-0.1.0/ebin
Elixir.What.Calendar.beam	     Elixir.What.Number.Cardinal.beam		Elixir.What.Number.beam
Elixir.What.Currency.beam	     Elixir.What.Number.Format.beam		Elixir.What.Rbnf.NumberSystem.beam
Elixir.What.Date.beam		     Elixir.What.Number.Formatter.Decimal.beam	Elixir.What.Rbnf.Ordinal.beam
Elixir.What.DateTime.Format.beam     Elixir.What.Number.Ordinal.beam		Elixir.What.Rbnf.Spellout.beam
Elixir.What.DateTime.Formatter.beam  Elixir.What.Number.PluralRule.Range.beam	Elixir.What.Time.beam
Elixir.What.DateTime.Relative.beam   Elixir.What.Number.Symbol.beam		Elixir.What.beam
Elixir.What.DateTime.beam	     Elixir.What.Number.System.beam		what.app
Elixir.What.Locale.beam		     Elixir.What.Number.Transliterate.beam
```

**Comment by coladarci** [comment] 2020-05-31 14:16
OK, I got to the bottom of this, and as we both (probably?) suspected; this was me doing something incorrect. 

I don't understand why this wouldn't have been caught by my tests, which is likely the only remaining piece to care about. So here are the steps to reproduce (and they do involve an umbrella):

1) Create an umbrella w/ two apps. App1, App2
2) In App1 and App2, add :ex_cldr as a dependency
3) In App1 add `ex_cldr_dates_times`
4) Define your CLDR in App2 (i.e create an App2.Cldr) and include `[Cldr.Number, Cldr.Calendar, Cldr.DateTime]` as providers. **This is the moment things went wrong; this shouldn't work because app2 doesn't include `ex_cldr_dates_times` as a dep. App1 shouldn't need any cldr deps. 
5) Write a test inside App2 to show that `App2.Cldr.DateTime.to_string(~N[2020-05-28 20:48:08], format: "EE, MMM d, y")` works; it shouldn't because when you run the tests from directly inside App2 (i.e you cd into apps/app2 and run `mix test`) it should fail because you've listed a provider that the app doesn't technically know about.

There is a very good chance this falls outside the hands of your packages; umbrella dependencies are a disaster and prone to all sort of problems, this being an example. But after you've invested so much time into helping me, I wanted to at least get you some steps to reproduce.

Please feel encouraged to close the issue when you have felt you've done all that is reasonable on your end.. thanks again for everything!

**Comment by kipcole9** [comment] 2020-05-31 14:29
Thanks very much for the explanation and for getting to the bottom of this. It still sounds like I should be able to provide some kind of "early warning" though.   At compile time when building a backend module there is a log message if a provider can't be found. So for whatever reason, the dependency seems to "leak" from one umbrella app to another.  Is that the intention in an umbrella?

Any thoughts on what I could do to detect this situation?

**Comment by kipcole9** [comment] 2020-05-31 14:34
BTW, some cool date/time interval formatting coming up in the next version.  So given two dates/times you'll be able to format them as

* `Jan 10–12, 2020` if the difference in dates is only days
* `Jan 10 – Feb 12, 2020` if the difference is months and 
* `Jan 10, 2020 – Feb 12, 2021` if the difference is years

Similar for times and date/times with some short, medium and long formats. `</ end of gratuitous ad>`

**Comment by coladarci** [comment] 2020-05-31 14:44
That's great! We do event software so your `money` lib + `cldr` is our entire world. date ranges are a big part of what we do so I'll be sure to try this out. Does it work w/ times? that'd be huge for us. `Jan 10th 9am - 2pm` versus `Jan 10th 9am - Jan 11th 5pm` etc. 

As far as deps leaking between apps, that's exactly the problem. They shouldn't but since there is a single mix.lock file not to mention a single config file, the idea that each app has it's own dependencies is a bit of a stretch. Where it normally bites us if you screw up your dependencies like this:

App1: {:greg, "1.0"}
App2: [no deps]

`App2.Greg.go!()`

This should fail because App2 doesn't include the dep. The problem is that if you run your tests from the root of the umbrella they typically WON'T fail. But if you `cd apps/app2` and run `mix test` they typically WILL fail.

**Comment by kipcole9** [comment] 2020-05-31 14:51
Yes, definitely for times and date times too. Of course localised.  It will auto detect the precision difference and apply the right format.  I finished the heavy lifting of ingesting the data from CLDR and generating the format functions.  Not just the public api so should be done by end of the week.

If you’re ok I think I’ll close this issue since I don’t think I have a way to remediate the issue.  I’ll put a warning in the docs since I think that’s about all I can do.

BTW, events (as in calendar events) with recurrence and mapping to schema.org and activity streams is probably my next project. You’re welcome to throw requirements at me about that.

**Comment by coladarci** [comment] 2020-05-31 14:56
Take a look at what we've done here - curious your thoughts on it! https://github.com/peek-travel/cocktail

**Closed** 2020-05-31 19:18 UTC
